### ISSUE TITLE
USWDS Adoption - Interviews - List & Schedule

### ISSUE THREAD

**Issue by jonadecker** [flexion/TTS-10x#29]
- [ ] pull together list of individuals and COP from Will
- [ ] coordinate with Will/Dan on access to COP
- [ ] schedule

**Comment by sstatz** [comment]
We've been working from this list of people to interview. https://docs.google.com/document/d/1XM9dC8S4vIVTtBZmxqcUtJZ1tmjHhryfT1fjFfYLExE/edit
